---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-image
  name: deployment-nginx-image
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-image
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-image
    spec:
      containers:
      - image: 102057119514.dkr.ecr.us-east-1.amazonaws.com/docker:1.0
        imagePullPolicy: Always
        name: nginx-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-image
  name: service-nginx-image
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nginx-image
  name: ingress-nginx-image
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-nginx-image
              port:
                number: 80
