name: Deploy HTML Application using docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: "docker"
      #     IMAGE_TAG: v2
      #   run: |
      #     echo $ECR_REGISTRY
      #     docker build -t $ECR_REGISTRY/$docker:$IMAGE_TAG
      #     docker push $ECR_REGISTRY/$docker:$IMAGE_TAG
      #     echo "::set-output name=image::$ECR_REGISTRY/$docker:$IMAGE_TAG"
      
      - name: Build docker image
        run: docker build -t new:1.0 nginx-image

      - name: Docker tag
        run: docker tag docker:latest 102057119514.dkr.ecr.us-east-1.amazonaws.com/docker:latest
