name: Deploy HTML Application using docker

on:
  push:
    branches: [ "main" ]
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 282354058591.dkr.ecr.us-east-1.amazonaws.com

      - name: Build docker image
        run: docker build -t johnwick nginx-image

      - name: Print Pipeline Runner Number
        run: echo "Runner Number:${{ github.run_number }}"

      - name: Docker tag
        run: docker tag johnwick:latest 282354058591.dkr.ecr.us-east-1.amazonaws.com/johnwick:${{ github.run_number }}

      - name: Docker push
        run: docker push 282354058591.dkr.ecr.us-east-1.amazonaws.com/johnwick:${{ github.run_number }}

      - name: install kubectl
        run: |
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.1/2023-09-14/bin/linux/amd64/kubectl
          curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.1/2023-09-14/bin/linux/amd64/kubectl.sha256
          sha256sum -c kubectl.sha256
          openssl sha1 -sha256 kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
          echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc

      - name: aws eks cluster update
        run: aws eks update-kubeconfig --name Johnwick-cluster --region us-east-1

      - name: kubectl config
        run: echo $KUBECONFIG

      - name: kube config
        run: KUBECONFIG=$HOME/.kube/config

      - name: kube config
        run: cat ~/.kube/config

      - name: kubectl pods
        run: kubectl get pods

      - name: Kubectl set command
        run: kubectl set image deployment/deployment-nginx-image test=282354058591.dkr.ecr.us-east-1.amazonaws.com/johnwick:${{ github.run_number }}
