name: Deploy HTML Application using docker

on:
  push:
    branches: [ "main" ]
   
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Login to Amazon ECR Private
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: "docker"
      #     IMAGE_TAG: v2
      #   run: |
      #     echo $ECR_REGISTRY
      #     docker build -t $ECR_REGISTRY/$docker:$IMAGE_TAG
      #     docker push $ECR_REGISTRY/$docker:$IMAGE_TAG
      #     echo "::set-output name=image::$ECR_REGISTRY/$docker:$IMAGE_TAG"

      - name: ECR login
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 282354058591.dkr.ecr.us-east-1.amazonaws.com
      
      - name: Build docker image
        run: docker build -t johnwick nginx-image

      - name: Docker tag
        run: docker tag johnwick:latest 282354058591.dkr.ecr.us-east-1.amazonaws.com/johnwick:latest

      - name: Docker push
        run: docker push 282354058591.dkr.ecr.us-east-1.amazonaws.com/johnwick:latest

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to local registry
        uses: ./
        with:
          context: ./nginx-image
          file: ./nginx-image/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
